try:
    print(hhh)
except Exception as result:
    print(result)